// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hjpzzQza_FRm6BCoPeLvFT4m7iK1loE',
    appId: '1:948688600584:web:eb7d6c0d265458d1a61bbd',
    messagingSenderId: '948688600584',
    projectId: 'ticktok-4951c',
    authDomain: 'ticktok-4951c.firebaseapp.com',
    storageBucket: 'ticktok-4951c.firebasestorage.app',
    measurementId: 'G-YYZ7CLCVMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-O-_T69wIFD02pQXg5wVZhru7FQtZDk',
    appId: '1:948688600584:android:3a6d3e35389661f9a61bbd',
    messagingSenderId: '948688600584',
    projectId: 'ticktok-4951c',
    storageBucket: 'ticktok-4951c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7mb3Du0_je64OyFjDhXWaHIdF6kn35HQ',
    appId: '1:948688600584:ios:e0e2c60ad73f3473a61bbd',
    messagingSenderId: '948688600584',
    projectId: 'ticktok-4951c',
    storageBucket: 'ticktok-4951c.firebasestorage.app',
    iosBundleId: 'com.ticktokclone',
  );

}